name = "Archimedes"
author = "Mulverine"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe4a23dac591cdfac7576c709c93a35040f5018de8b28cfebde698a0e1c26c39"

[versions]
fabric = "0.13.2"
minecraft = "1.17.1"
