name = "picoblaze"
filename = "picoblaze-1.2.2.jar"
side = "server"

[download]
url = "https://github.com/lolgeny/picoblaze/releases/download/1.2.2/picoblaze-1.2.2.jar"

# A number of tools can generate the hash for you, including 7-zip and sha256sum
# packwiz supports a number of hashes, including sha256, sha512, sha1 and md5
hash-format = "sha256"
hash = "B0D33C8B06C6AA8447D5234EBC3FF50E7C72920066D28B275BAFBF19D9D56CCD"